### ISSUE TITLE
使用 kityformula 化出来的 能否保存为 LaTeX 呢？

### ISSUE THREAD

**Issue by leixu2txtek** [fex-team/kityformula#4]
使用 kityformula 化出来的 能否保存为 LaTeX 呢？

因为不想保存为图片，仅想保存 LaTeX 然后 再做渲染。。

不知能否做到呀？

期待回复

**Comment by yaLingzh** [comment]
是可以的
已经验证过了
formulaEditor.execCommand('get.source')
直接得到 LaTeX

**Comment by leixu2txtek** [comment]
时间过的太久了，我都忘记了。
这个项目还活着？
